name: caresignal
version: '1.0.0'
profile: caresignal

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

models:
  caresignal:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts